"""Emit an AudioXL patcher (.reds) from the diff between two audio-metadata exports.

Point this at vanilla and at a mods exported metadata, and it writes the RedScript that reproduces that mods changes as live edits.

  python gen_record_overrides.py --base <vanilla.json> --modded <mod.json> \
      --module TheLoudening --class LoudeningPatcher --out <path.reds>

Phantom Liberty records live in a second resource, so pass --ep1-base / --ep1-modded to emit an
ApplyEP1 block alongside Apply. --exclude drops a record by name: shipped archives pick up edits
from whatever else was in the author's load order, and those are not the mod.
"""
import argparse, os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from audiomd import index

MAX_PER_FUNC = 60

def val(x):
    return x.get('$value') if isinstance(x, dict) else x

def is_cname(x):
    return isinstance(x, dict) and x.get('$type') == 'CName'

def is_cname_array(x):
    return isinstance(x, list) and all(is_cname(i) for i in x) and len(x) > 0

def collect(base_path, mod_path, exclude=()):
    base, _, _ = index(base_path)
    mod, _, _ = index(mod_path)
    out, skipped, dropped = [], [], []
    for key in sorted(set(base) & set(mod)):
        if key[1] in exclude:
            if base[key][0] != mod[key][0]:
                dropped.append(key)
            continue
        if base[key][0] == mod[key][0]:
            continue
        a, b = base[key][1], mod[key][1]
        edits = []
        for prop in sorted(set(a) | set(b)):
            if a.get(prop) == b.get(prop):
                continue
            new = b.get(prop)
            if is_cname(new):
                edits.append((prop, 'cname', val(new)))
            elif is_cname_array(new):
                edits.append((prop, 'cnames', [val(i) for i in new]))
            else:
                skipped.append((key, prop, type(new).__name__))
        if edits:
            out.append((key[0], key[1], edits))
    added = sorted(set(mod) - set(base))
    return out, skipped, added, dropped

def phase(w, records, entry, chunk_prefix, var_prefix, applied, missed):
    """Emit one Apply* entry point plus its chunk bodies. Base and EP1 differ only in these names."""
    w(f"  public func {entry}(md: ref<audioCookedMetadataResource>) -> Void {{")
    chunks = [records[i:i + MAX_PER_FUNC] for i in range(0, len(records), MAX_PER_FUNC)]
    for n in range(len(chunks)):
        w(f"    this.{chunk_prefix}{n}(md);")
    w("  }")

    idx = 0
    for n, chunk in enumerate(chunks):
        w("")
        w(f"  private func {chunk_prefix}{n}(md: ref<audioCookedMetadataResource>) -> Void {{")
        w("    let sys = AudioXLSystem.Get();")
        for rtype, rname, edits in chunk:
            var = f"{var_prefix}{idx}"
            idx += 1
            w(f"    let {var} = sys.FindRecord(md, n\"{rname}\") as {rtype};")
            w(f"    if IsDefined({var}) {{")
            for prop, kind, value in edits:
                if kind == 'cname':
                    w(f'      {var}.{prop} = n"{value}";')
                else:
                    w(f"      ArrayClear({var}.{prop});")
                    for item in value:
                        w(f'      ArrayPush({var}.{prop}, n"{item}");')
            w(f"      this.{applied} += 1;")
            w("    } else {")
            w(f"      this.{missed} += 1;")
            w("    }")
        w("  }")

def emit(records, ep1_records, module, cls, mod_label):
    L = []
    w = L.append
    w(f"// {mod_label} as live record edits - generated by tools/gen_record_overrides.py, do not hand-edit.")
    w("//")
    w("// Reproduces the mods metadata changes against the resource the game already loaded, so")
    w("// nothing replaces cooked_metadata.audio_metadata and other audio mods still work.")
    w(f"module {module}")
    w("")
    w("import AudioXL.*")
    w("")
    w(f"public class {cls} extends AudioXLPatcher {{")
    w(f'  public func Name() -> String {{ return "{mod_label}"; }}')
    w("")
    phase(w, records, "Apply", "Chunk", "rec", "applied", "missed")
    if ep1_records:
        w("")
        w("  // Phantom Liberty records - a second resource, handed in separately by AudioXL.")
        phase(w, ep1_records, "ApplyEP1", "EP1Chunk", "ep", "appliedEP1", "missedEP1")
    w("}")
    w("")
    return "\n".join(L)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--base', required=True)
    ap.add_argument('--modded', required=True)
    ap.add_argument('--module', required=True)
    ap.add_argument('--class', dest='cls', required=True)
    ap.add_argument('--label')
    ap.add_argument('--out', required=True)
    ap.add_argument('--ep1-base', dest='ep1_base')
    ap.add_argument('--ep1-modded', dest='ep1_modded')
    ap.add_argument('--exclude', action='append', default=[],
                    help='record name to leave out; repeat per record')
    a = ap.parse_args()

    records, skipped, added, dropped = collect(a.base, a.modded, set(a.exclude))
    ep1_records, ep1_skipped, ep1_added, ep1_dropped = [], [], [], []
    if a.ep1_base and a.ep1_modded:
        ep1_records, ep1_skipped, ep1_added, ep1_dropped = collect(
            a.ep1_base, a.ep1_modded, set(a.exclude))
        skipped += ep1_skipped
        dropped += ep1_dropped
        added += ep1_added

    n_edits = sum(len(e) for _, _, e in records)
    print(f"{len(records)} records changed, {n_edits} property edits")
    by = {}
    for rtype, _, e in records:
        by[rtype] = by.get(rtype, 0) + 1
    print(f"  by type: {by}")
    if ep1_records:
        n_ep1 = sum(len(e) for _, _, e in ep1_records)
        print(f"EP1: {len(ep1_records)} records changed, {n_ep1} property edits")

    if dropped:
        print(f"\n  EXCLUDED {len(dropped)} records the mod changes but you asked to skip:")
        for k in dropped:
            print(f"      {k[0]}  {k[1]}")
    if added:
        print(f"\n  NOTE: {len(added)} records are added by the mod - a patcher cannot create records.")
        print("  Ship those as an AudioXL contribution archive instead:")
        for k in added[:8]:
            print(f"      {k[0]}  {k[1]}")
    if skipped:
        print(f"\n  SKIPPED {len(skipped)} non-CName edits (not safe to emit blindly):")
        for k, prop, kind in skipped[:8]:
            print(f"      {k[0]} {k[1]}.{prop}  ({kind})")

    text = emit(records, ep1_records, a.module, a.cls, a.label or a.module)
    os.makedirs(os.path.dirname(os.path.abspath(a.out)), exist_ok=True)
    with open(a.out, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(text)
    print(f"\nwrote {a.out}  ({len(text.splitlines())} lines)")
    return 0

if __name__ == '__main__':
    sys.exit(main())
