"""Emit an AudioXL patcher (.reds) from the diff between two audio-metadata exports.

Point this at vanilla and at a mods exported metadata, and it writes the RedScript that reproduces that mods changes as live edits.

  python gen_record_overrides.py --base <vanilla.json> --modded <mod.json> \
      --module TheLoudening --class LoudeningPatcher --out <path.reds>

"""
import argparse, os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from audiomd import index

MAX_PER_FUNC = 60

def val(x):
    return x.get('$value') if isinstance(x, dict) else x

def is_cname(x):
    return isinstance(x, dict) and x.get('$type') == 'CName'

def is_cname_array(x):
    return isinstance(x, list) and all(is_cname(i) for i in x) and len(x) > 0

def collect(base_path, mod_path):
    base, _, _ = index(base_path)
    mod, _, _ = index(mod_path)
    out, skipped = [], []
    for key in sorted(set(base) & set(mod)):
        if base[key][0] == mod[key][0]:
            continue
        a, b = base[key][1], mod[key][1]
        edits = []
        for prop in sorted(set(a) | set(b)):
            if a.get(prop) == b.get(prop):
                continue
            new = b.get(prop)
            if is_cname(new):
                edits.append((prop, 'cname', val(new)))
            elif is_cname_array(new):
                edits.append((prop, 'cnames', [val(i) for i in new]))
            else:
                skipped.append((key, prop, type(new).__name__))
        if edits:
            out.append((key[0], key[1], edits))
    added = sorted(set(mod) - set(base))
    return out, skipped, added

def emit(records, module, cls, mod_label):
    L = []
    w = L.append
    w(f"// {mod_label} as live record edits - generated by tools/gen_record_overrides.py, do not hand-edit.")
    w("//")
    w("// Reproduces the mods metadata changes against the resource the game already loaded, so")
    w("// nothing replaces cooked_metadata.audio_metadata and other audio mods still work.")
    w(f"module {module}")
    w("")
    w("import AudioXL.*")
    w("")
    w(f"public class {cls} extends AudioXLPatcher {{")
    w(f'  public func Name() -> String {{ return "{mod_label}"; }}')
    w("")
    w("  public func Apply(md: ref<audioCookedMetadataResource>) -> Void {")
    chunks = [records[i:i + MAX_PER_FUNC] for i in range(0, len(records), MAX_PER_FUNC)]
    for n in range(len(chunks)):
        w(f"    this.Chunk{n}(md);")
    w("  }")

    idx = 0
    for n, chunk in enumerate(chunks):
        w("")
        w(f"  private func Chunk{n}(md: ref<audioCookedMetadataResource>) -> Void {{")
        w("    let sys = AudioXLSystem.Get();")
        for rtype, rname, edits in chunk:
            var = f"rec{idx}"
            idx += 1
            w(f"    let {var} = sys.FindRecord(md, n\"{rname}\") as {rtype};")
            w(f"    if IsDefined({var}) {{")
            for prop, kind, value in edits:
                if kind == 'cname':
                    w(f'      {var}.{prop} = n"{value}";')
                else:
                    w(f"      ArrayClear({var}.{prop});")
                    for item in value:
                        w(f'      ArrayPush({var}.{prop}, n"{item}");')
            w("      this.applied += 1;")
            w("    } else {")
            w("      this.missed += 1;")
            w("    }")
        w("  }")
    w("}")
    w("")
    return "\n".join(L)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--base', required=True)
    ap.add_argument('--modded', required=True)
    ap.add_argument('--module', required=True)
    ap.add_argument('--class', dest='cls', required=True)
    ap.add_argument('--label')
    ap.add_argument('--out', required=True)
    a = ap.parse_args()

    records, skipped, added = collect(a.base, a.modded)
    n_edits = sum(len(e) for _, _, e in records)
    print(f"{len(records)} records changed, {n_edits} property edits")
    by = {}
    for rtype, _, e in records:
        by[rtype] = by.get(rtype, 0) + 1
    print(f"  by type: {by}")

    if added:
        print(f"\n  NOTE: {len(added)} records are added by the mod - a patcher cannot create records.")
        print("  Ship those as an AudioXL contribution archive instead:")
        for k in added[:8]:
            print(f"      {k[0]}  {k[1]}")
    if skipped:
        print(f"\n  SKIPPED {len(skipped)} non-CName edits (not safe to emit blindly):")
        for k, prop, kind in skipped[:8]:
            print(f"      {k[0]} {k[1]}.{prop}  ({kind})")

    text = emit(records, a.module, a.cls, a.label or a.module)
    os.makedirs(os.path.dirname(os.path.abspath(a.out)), exist_ok=True)
    with open(a.out, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(text)
    print(f"\nwrote {a.out}  ({len(text.splitlines())} lines)")
    return 0

if __name__ == '__main__':
    sys.exit(main())
